# Generated by Django 6.0.4 on 2026-04-10 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carregamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motorista', models.CharField(max_length=100)),
                ('placa', models.CharField(max_length=10)),
                ('distribuidora', models.CharField(max_length=50)),
                ('transportador', models.CharField(max_length=50)),
                ('litragem_sem_excesso', models.IntegerField()),
                ('ordem', models.CharField(max_length=10)),
                ('situacao', models.CharField(choices=[('FINALIZADO', 'Finalizado'), ('CARREGANDO', 'Carregando'), ('PATIO', 'Pátio')], max_length=20)),
                ('lacres', models.IntegerField()),
            ],
        ),
    ]
