# Generated by Django 6.0.4 on 2026-04-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carregamento',
            options={'ordering': ['id'], 'verbose_name': 'carregamento', 'verbose_name_plural': 'carregamentos'},
        ),
        migrations.AlterField(
            model_name='carregamento',
            name='distribuidora',
            field=models.CharField(max_length=50, verbose_name='distribuidora'),
        ),
        migrations.AlterField(
            model_name='carregamento',
            name='lacres',
            field=models.IntegerField(verbose_name='lacres'),
        ),
        migrations.AlterField(
            model_name='carregamento',
            name='litragem_sem_excesso',
            field=models.IntegerField(verbose_name='litragem sem excesso'),
        ),
        migrations.AlterField(
            model_name='carregamento',
            name='motorista',
            field=models.CharField(max_length=100, verbose_name='motorista'),
        ),
        migrations.AlterField(
            model_name='carregamento',
            name='ordem',
            field=models.CharField(choices=[('SIM', 'SIM'), ('NAO TEM', 'NAO TEM')], max_length=10, verbose_name='ordem'),
        ),
        migrations.AlterField(
            model_name='carregamento',
            name='placa',
            field=models.CharField(max_length=10, verbose_name='placa'),
        ),
        migrations.AlterField(
            model_name='carregamento',
            name='situacao',
            field=models.CharField(choices=[('FINALIZADO', 'Finalizado'), ('CARREGANDO', 'Carregando'), ('PATIO', 'Patio')], max_length=20, verbose_name='situacao'),
        ),
        migrations.AlterField(
            model_name='carregamento',
            name='transportador',
            field=models.CharField(max_length=50, verbose_name='transportador'),
        ),
    ]
