# Generated by Django 6.0.4 on 2026-04-10 17:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_carregamento_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carregamento',
            name='data_hora_cadastro',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='data/hora cadastro'),
        ),
    ]
