# Generated by Django 6.0.4 on 2026-04-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_carregamento_data_hora_cadastro'),
    ]

    operations = [
        migrations.AddField(
            model_name='carregamento',
            name='alterado_por',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='alterado por'),
        ),
        migrations.AddField(
            model_name='carregamento',
            name='data_hora_alteracao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='data/hora alteração'),
        ),
        migrations.AlterField(
            model_name='carregamento',
            name='ordem',
            field=models.CharField(choices=[('SIM', 'SIM'), ('NÃO TEM', 'NÃO TEM')], max_length=10, verbose_name='ordem'),
        ),
    ]
