# Generated by Django 6.0.4 on 2026-04-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_carregamento_alterado_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carregamento',
            name='lacres',
            field=models.CharField(choices=[('3', '3'), ('6', '6'), ('12', '12'), ('15', '15'), ('18', '18'), ('21', '21'), ('24', '24')], max_length=10, verbose_name='lacres'),
        ),
    ]
